//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.GIS
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// SourceDataLink.
    /// </summary>
    // *** Start programmer edit section *** (SourceDataLink CustomAttributes)

    // *** End programmer edit section *** (SourceDataLink CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SourceDataLinkE", new string[] {
            "MapObjectSetting.TypeName",
            "MapObjectSetting.ListForm",
            "MapObjectSetting.EditForm",
            "MapObjectSetting.MultEditForm",
            "MapObjectSetting.Title",
            "MapObjectSetting",
            "Source",
            "AllowShow",
            "AllowCreate",
            "AllowLink",
            "AllowMultCreate"})]
    [AssociatedDetailViewAttribute("SourceDataLinkE", "SourceDataLinkParameter", "SourceDataLinkParameterD", true, "", "", true, new string[] {
            ""})]
    public class SourceDataLink : ICSSoft.STORMNET.DataObject
    {
        
        private string fSource;
        
        private bool fAllowShow;
        
        private bool fAllowCreate;
        
        private bool fAllowMultCreate;
        
        private bool fAllowLink;
        
        private NewPlatform.Flexberry.GIS.MapObjectSetting fMapObjectSetting;
        
        private NewPlatform.Flexberry.GIS.DetailArrayOfSourceDataLinkParameter fSourceDataLinkParameter;
        
        // *** Start programmer edit section *** (SourceDataLink CustomMembers)

        // *** End programmer edit section *** (SourceDataLink CustomMembers)

        
        /// <summary>
        /// Source.
        /// </summary>
        // *** Start programmer edit section *** (SourceDataLink.Source CustomAttributes)

        // *** End programmer edit section *** (SourceDataLink.Source CustomAttributes)
        [StrLen(255)]
        public virtual string Source
        {
            get
            {
                // *** Start programmer edit section *** (SourceDataLink.Source Get start)

                // *** End programmer edit section *** (SourceDataLink.Source Get start)
                string result = this.fSource;
                // *** Start programmer edit section *** (SourceDataLink.Source Get end)

                // *** End programmer edit section *** (SourceDataLink.Source Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SourceDataLink.Source Set start)

                // *** End programmer edit section *** (SourceDataLink.Source Set start)
                this.fSource = value;
                // *** Start programmer edit section *** (SourceDataLink.Source Set end)

                // *** End programmer edit section *** (SourceDataLink.Source Set end)
            }
        }
        
        /// <summary>
        /// AllowShow.
        /// </summary>
        // *** Start programmer edit section *** (SourceDataLink.AllowShow CustomAttributes)

        // *** End programmer edit section *** (SourceDataLink.AllowShow CustomAttributes)
        public virtual bool AllowShow
        {
            get
            {
                // *** Start programmer edit section *** (SourceDataLink.AllowShow Get start)

                // *** End programmer edit section *** (SourceDataLink.AllowShow Get start)
                bool result = this.fAllowShow;
                // *** Start programmer edit section *** (SourceDataLink.AllowShow Get end)

                // *** End programmer edit section *** (SourceDataLink.AllowShow Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SourceDataLink.AllowShow Set start)

                // *** End programmer edit section *** (SourceDataLink.AllowShow Set start)
                this.fAllowShow = value;
                // *** Start programmer edit section *** (SourceDataLink.AllowShow Set end)

                // *** End programmer edit section *** (SourceDataLink.AllowShow Set end)
            }
        }
        
        /// <summary>
        /// AllowCreate.
        /// </summary>
        // *** Start programmer edit section *** (SourceDataLink.AllowCreate CustomAttributes)

        // *** End programmer edit section *** (SourceDataLink.AllowCreate CustomAttributes)
        public virtual bool AllowCreate
        {
            get
            {
                // *** Start programmer edit section *** (SourceDataLink.AllowCreate Get start)

                // *** End programmer edit section *** (SourceDataLink.AllowCreate Get start)
                bool result = this.fAllowCreate;
                // *** Start programmer edit section *** (SourceDataLink.AllowCreate Get end)

                // *** End programmer edit section *** (SourceDataLink.AllowCreate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SourceDataLink.AllowCreate Set start)

                // *** End programmer edit section *** (SourceDataLink.AllowCreate Set start)
                this.fAllowCreate = value;
                // *** Start programmer edit section *** (SourceDataLink.AllowCreate Set end)

                // *** End programmer edit section *** (SourceDataLink.AllowCreate Set end)
            }
        }
        
        /// <summary>
        /// AllowMultCreate.
        /// </summary>
        // *** Start programmer edit section *** (SourceDataLink.AllowMultCreate CustomAttributes)

        // *** End programmer edit section *** (SourceDataLink.AllowMultCreate CustomAttributes)
        public virtual bool AllowMultCreate
        {
            get
            {
                // *** Start programmer edit section *** (SourceDataLink.AllowMultCreate Get start)

                // *** End programmer edit section *** (SourceDataLink.AllowMultCreate Get start)
                bool result = this.fAllowMultCreate;
                // *** Start programmer edit section *** (SourceDataLink.AllowMultCreate Get end)

                // *** End programmer edit section *** (SourceDataLink.AllowMultCreate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SourceDataLink.AllowMultCreate Set start)

                // *** End programmer edit section *** (SourceDataLink.AllowMultCreate Set start)
                this.fAllowMultCreate = value;
                // *** Start programmer edit section *** (SourceDataLink.AllowMultCreate Set end)

                // *** End programmer edit section *** (SourceDataLink.AllowMultCreate Set end)
            }
        }
        
        /// <summary>
        /// AllowLink.
        /// </summary>
        // *** Start programmer edit section *** (SourceDataLink.AllowLink CustomAttributes)

        // *** End programmer edit section *** (SourceDataLink.AllowLink CustomAttributes)
        public virtual bool AllowLink
        {
            get
            {
                // *** Start programmer edit section *** (SourceDataLink.AllowLink Get start)

                // *** End programmer edit section *** (SourceDataLink.AllowLink Get start)
                bool result = this.fAllowLink;
                // *** Start programmer edit section *** (SourceDataLink.AllowLink Get end)

                // *** End programmer edit section *** (SourceDataLink.AllowLink Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SourceDataLink.AllowLink Set start)

                // *** End programmer edit section *** (SourceDataLink.AllowLink Set start)
                this.fAllowLink = value;
                // *** Start programmer edit section *** (SourceDataLink.AllowLink Set end)

                // *** End programmer edit section *** (SourceDataLink.AllowLink Set end)
            }
        }
        
        /// <summary>
        /// SourceDataLink.
        /// </summary>
        // *** Start programmer edit section *** (SourceDataLink.MapObjectSetting CustomAttributes)

        // *** End programmer edit section *** (SourceDataLink.MapObjectSetting CustomAttributes)
        [PropertyStorage(new string[] {
                "MapObjectSetting"})]
        [NotNull()]
        public virtual NewPlatform.Flexberry.GIS.MapObjectSetting MapObjectSetting
        {
            get
            {
                // *** Start programmer edit section *** (SourceDataLink.MapObjectSetting Get start)

                // *** End programmer edit section *** (SourceDataLink.MapObjectSetting Get start)
                NewPlatform.Flexberry.GIS.MapObjectSetting result = this.fMapObjectSetting;
                // *** Start programmer edit section *** (SourceDataLink.MapObjectSetting Get end)

                // *** End programmer edit section *** (SourceDataLink.MapObjectSetting Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SourceDataLink.MapObjectSetting Set start)

                // *** End programmer edit section *** (SourceDataLink.MapObjectSetting Set start)
                this.fMapObjectSetting = value;
                // *** Start programmer edit section *** (SourceDataLink.MapObjectSetting Set end)

                // *** End programmer edit section *** (SourceDataLink.MapObjectSetting Set end)
            }
        }
        
        /// <summary>
        /// SourceDataLink.
        /// </summary>
        // *** Start programmer edit section *** (SourceDataLink.SourceDataLinkParameter CustomAttributes)

        // *** End programmer edit section *** (SourceDataLink.SourceDataLinkParameter CustomAttributes)
        public virtual NewPlatform.Flexberry.GIS.DetailArrayOfSourceDataLinkParameter SourceDataLinkParameter
        {
            get
            {
                // *** Start programmer edit section *** (SourceDataLink.SourceDataLinkParameter Get start)

                // *** End programmer edit section *** (SourceDataLink.SourceDataLinkParameter Get start)
                if ((this.fSourceDataLinkParameter == null))
                {
                    this.fSourceDataLinkParameter = new NewPlatform.Flexberry.GIS.DetailArrayOfSourceDataLinkParameter(this);
                }
                NewPlatform.Flexberry.GIS.DetailArrayOfSourceDataLinkParameter result = this.fSourceDataLinkParameter;
                // *** Start programmer edit section *** (SourceDataLink.SourceDataLinkParameter Get end)

                // *** End programmer edit section *** (SourceDataLink.SourceDataLinkParameter Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SourceDataLink.SourceDataLinkParameter Set start)

                // *** End programmer edit section *** (SourceDataLink.SourceDataLinkParameter Set start)
                this.fSourceDataLinkParameter = value;
                // *** Start programmer edit section *** (SourceDataLink.SourceDataLinkParameter Set end)

                // *** End programmer edit section *** (SourceDataLink.SourceDataLinkParameter Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SourceDataLinkE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SourceDataLinkE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SourceDataLinkE", typeof(NewPlatform.Flexberry.GIS.SourceDataLink));
                }
            }
        }
    }
}
