//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.GIS
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// LayerLink.
    /// </summary>
    // *** Start programmer edit section *** (LayerLink CustomAttributes)

    // *** End programmer edit section *** (LayerLink CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("LayerLinkD", new string[] {
            "MapObjectSetting as \'Тип\'",
            "MapObjectSetting.TypeName as \'Тип объекта\'",
            "MapObjectSetting.ListForm as \'Списковая форма\'",
            "MapObjectSetting.EditForm as \'Форма редактирования\'",
            "Layer",
            "Layer.Name as \'Слой\'",
            "AllowShow as \'Показывать\'"}, Hidden=new string[] {
            "MapObjectSetting.TypeName",
            "MapObjectSetting.ListForm",
            "MapObjectSetting.EditForm",
            "Layer",
            "Layer.Name"})]
    [AssociatedDetailViewAttribute("LayerLinkD", "Parameters", "LinkParameterD", true, "", "Параметры связи", true, new string[] {
            ""})]
    [View("LayerLinkE", new string[] {
            "Layer as \'Слой карты\'",
            "MapObjectSetting",
            "AllowShow as \'Показывать\'"})]
    [View("LayerLinkEF", new string[] {
            "Layer as \'Слой карты\'",
            "Layer.Name",
            "MapObjectSetting",
            "AllowShow as \'Показывать\'"}, Hidden=new string[] {
            "Layer.Name"})]
    [AssociatedDetailViewAttribute("LayerLinkEF", "Parameters", "LinkParameterD", true, "", "", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("LayerLinkEF", "Layer", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("LayerLinkI", new string[] {
            "Layer",
            "MapObjectSetting.ListForm",
            "MapObjectSetting.EditForm",
            "AllowShow as \'Показывать\'"})]
    [AssociatedDetailViewAttribute("LayerLinkI", "Parameters", "LinkParameterD", true, "", "Параметры связи", true, new string[] {
            ""})]
    [View("LayerLinkL", new string[] {
            "MapObjectSetting",
            "Layer",
            "Layer.Name as \'Слой\'",
            "AllowShow as \'Показывать\'"}, Hidden=new string[] {
            "MapObjectSetting",
            "Layer"})]
    [AssociatedDetailViewAttribute("LayerLinkL", "Parameters", "LinkParameterD", true, "", "Параметры связи", true, new string[] {
            ""})]
    [View("LayerLinkQ", new string[] {
            "Layer",
            "MapObjectSetting",
            "AllowShow as \'Показывать\'"})]
    [AssociatedDetailViewAttribute("LayerLinkQ", "Parameters", "LinkParameterD", true, "", "Параметры связи", true, new string[] {
            ""})]
    public class LayerLink : ICSSoft.STORMNET.DataObject
    {
        
        private bool fAllowShow = false;
        
        private NewPlatform.Flexberry.GIS.MapObjectSetting fMapObjectSetting;
        
        private NewPlatform.Flexberry.GIS.DetailArrayOfLinkParameter fParameters;
        
        private NewPlatform.Flexberry.GIS.MapLayer fLayer;
        
        // *** Start programmer edit section *** (LayerLink CustomMembers)

        // *** End programmer edit section *** (LayerLink CustomMembers)

        
        /// <summary>
        /// AllowShow.
        /// </summary>
        // *** Start programmer edit section *** (LayerLink.AllowShow CustomAttributes)

        // *** End programmer edit section *** (LayerLink.AllowShow CustomAttributes)
        public virtual bool AllowShow
        {
            get
            {
                // *** Start programmer edit section *** (LayerLink.AllowShow Get start)

                // *** End programmer edit section *** (LayerLink.AllowShow Get start)
                bool result = this.fAllowShow;
                // *** Start programmer edit section *** (LayerLink.AllowShow Get end)

                // *** End programmer edit section *** (LayerLink.AllowShow Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LayerLink.AllowShow Set start)

                // *** End programmer edit section *** (LayerLink.AllowShow Set start)
                this.fAllowShow = value;
                // *** Start programmer edit section *** (LayerLink.AllowShow Set end)

                // *** End programmer edit section *** (LayerLink.AllowShow Set end)
            }
        }
        
        /// <summary>
        /// LayerLink.
        /// </summary>
        // *** Start programmer edit section *** (LayerLink.MapObjectSetting CustomAttributes)

        // *** End programmer edit section *** (LayerLink.MapObjectSetting CustomAttributes)
        [PropertyStorage(new string[] {
                "MapObjectSetting"})]
        [NotNull()]
        public virtual NewPlatform.Flexberry.GIS.MapObjectSetting MapObjectSetting
        {
            get
            {
                // *** Start programmer edit section *** (LayerLink.MapObjectSetting Get start)

                // *** End programmer edit section *** (LayerLink.MapObjectSetting Get start)
                NewPlatform.Flexberry.GIS.MapObjectSetting result = this.fMapObjectSetting;
                // *** Start programmer edit section *** (LayerLink.MapObjectSetting Get end)

                // *** End programmer edit section *** (LayerLink.MapObjectSetting Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LayerLink.MapObjectSetting Set start)

                // *** End programmer edit section *** (LayerLink.MapObjectSetting Set start)
                this.fMapObjectSetting = value;
                // *** Start programmer edit section *** (LayerLink.MapObjectSetting Set end)

                // *** End programmer edit section *** (LayerLink.MapObjectSetting Set end)
            }
        }
        
        /// <summary>
        /// LayerLink.
        /// </summary>
        // *** Start programmer edit section *** (LayerLink.Parameters CustomAttributes)

        // *** End programmer edit section *** (LayerLink.Parameters CustomAttributes)
        public virtual NewPlatform.Flexberry.GIS.DetailArrayOfLinkParameter Parameters
        {
            get
            {
                // *** Start programmer edit section *** (LayerLink.Parameters Get start)

                // *** End programmer edit section *** (LayerLink.Parameters Get start)
                if ((this.fParameters == null))
                {
                    this.fParameters = new NewPlatform.Flexberry.GIS.DetailArrayOfLinkParameter(this);
                }
                NewPlatform.Flexberry.GIS.DetailArrayOfLinkParameter result = this.fParameters;
                // *** Start programmer edit section *** (LayerLink.Parameters Get end)

                // *** End programmer edit section *** (LayerLink.Parameters Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LayerLink.Parameters Set start)

                // *** End programmer edit section *** (LayerLink.Parameters Set start)
                this.fParameters = value;
                // *** Start programmer edit section *** (LayerLink.Parameters Set end)

                // *** End programmer edit section *** (LayerLink.Parameters Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.GIS.MapLayer.
        /// </summary>
        // *** Start programmer edit section *** (LayerLink.Layer CustomAttributes)

        // *** End programmer edit section *** (LayerLink.Layer CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Layer"})]
        public virtual NewPlatform.Flexberry.GIS.MapLayer Layer
        {
            get
            {
                // *** Start programmer edit section *** (LayerLink.Layer Get start)

                // *** End programmer edit section *** (LayerLink.Layer Get start)
                NewPlatform.Flexberry.GIS.MapLayer result = this.fLayer;
                // *** Start programmer edit section *** (LayerLink.Layer Get end)

                // *** End programmer edit section *** (LayerLink.Layer Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LayerLink.Layer Set start)

                // *** End programmer edit section *** (LayerLink.Layer Set start)
                this.fLayer = value;
                // *** Start programmer edit section *** (LayerLink.Layer Set end)

                // *** End programmer edit section *** (LayerLink.Layer Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "LayerLinkD" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LayerLinkD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LayerLinkD", typeof(NewPlatform.Flexberry.GIS.LayerLink));
                }
            }
            
            /// <summary>
            /// "LayerLinkE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LayerLinkE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LayerLinkE", typeof(NewPlatform.Flexberry.GIS.LayerLink));
                }
            }
            
            /// <summary>
            /// Для формы редактирования.
            /// </summary>
            public static ICSSoft.STORMNET.View LayerLinkEF
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LayerLinkEF", typeof(NewPlatform.Flexberry.GIS.LayerLink));
                }
            }
            
            /// <summary>
            /// Для загрузка данных при идентификации.
            /// </summary>
            public static ICSSoft.STORMNET.View LayerLinkI
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LayerLinkI", typeof(NewPlatform.Flexberry.GIS.LayerLink));
                }
            }
            
            /// <summary>
            /// Для списка на форме MOS.
            /// </summary>
            public static ICSSoft.STORMNET.View LayerLinkL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LayerLinkL", typeof(NewPlatform.Flexberry.GIS.LayerLink));
                }
            }
            
            /// <summary>
            /// Для query запроса при переходе на карту.
            /// </summary>
            public static ICSSoft.STORMNET.View LayerLinkQ
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LayerLinkQ", typeof(NewPlatform.Flexberry.GIS.LayerLink));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of LayerLink.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfLayerLink CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfLayerLink CustomAttributes)
    public class DetailArrayOfLayerLink : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.GIS.DetailArrayOfLayerLink members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.GIS.DetailArrayOfLayerLink members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type LayerLink by index.
        /// </summary>
        /// <summary>
        /// Adds object with type LayerLink.
        /// </summary>
        public DetailArrayOfLayerLink(NewPlatform.Flexberry.GIS.MapLayer fMapLayer) : 
                base(typeof(LayerLink), ((ICSSoft.STORMNET.DataObject)(fMapLayer)))
        {
        }
        
        public NewPlatform.Flexberry.GIS.LayerLink this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.GIS.LayerLink)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.GIS.LayerLink dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
