//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.GIS
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// LinkMetadata.
    /// </summary>
    // *** Start programmer edit section *** (LinkMetadata CustomAttributes)

    // *** End programmer edit section *** (LinkMetadata CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "AllowShow as \'Показывать\'",
            "Layer as \'Слой\'",
            "MapObjectSetting as \'Настройка\'"})]
    [AssociatedDetailViewAttribute("AuditView", "Parameters", "AuditView", true, "", "Параметры связи", true, new string[] {
            ""})]
    [View("LinkMetadataD", new string[] {
            "Layer as \'Слой\'",
            "Layer.Name",
            "MapObjectSetting as \'Настройка\'",
            "MapObjectSetting.TypeName",
            "AllowShow as \'Показывать\'"}, Hidden=new string[] {
            "Layer.Name",
            "MapObjectSetting.TypeName"})]
    [AssociatedDetailViewAttribute("LinkMetadataD", "Parameters", "ParameterMetadataD", true, "", "Параметры связи", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("LinkMetadataD", "Layer", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("LinkMetadataD", "MapObjectSetting", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "TypeName")]
    public class LinkMetadata : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private bool fAllowShow = false;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private NewPlatform.Flexberry.GIS.MapObjectSetting fMapObjectSetting;
        
        private NewPlatform.Flexberry.GIS.DetailArrayOfParameterMetadata fParameters;
        
        private NewPlatform.Flexberry.GIS.LayerMetadata fLayer;
        
        // *** Start programmer edit section *** (LinkMetadata CustomMembers)

        // *** End programmer edit section *** (LinkMetadata CustomMembers)

        
        /// <summary>
        /// AllowShow.
        /// </summary>
        // *** Start programmer edit section *** (LinkMetadata.AllowShow CustomAttributes)

        // *** End programmer edit section *** (LinkMetadata.AllowShow CustomAttributes)
        public virtual bool AllowShow
        {
            get
            {
                // *** Start programmer edit section *** (LinkMetadata.AllowShow Get start)

                // *** End programmer edit section *** (LinkMetadata.AllowShow Get start)
                bool result = this.fAllowShow;
                // *** Start programmer edit section *** (LinkMetadata.AllowShow Get end)

                // *** End programmer edit section *** (LinkMetadata.AllowShow Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LinkMetadata.AllowShow Set start)

                // *** End programmer edit section *** (LinkMetadata.AllowShow Set start)
                this.fAllowShow = value;
                // *** Start programmer edit section *** (LinkMetadata.AllowShow Set end)

                // *** End programmer edit section *** (LinkMetadata.AllowShow Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (LinkMetadata.CreateTime CustomAttributes)

        // *** End programmer edit section *** (LinkMetadata.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (LinkMetadata.CreateTime Get start)

                // *** End programmer edit section *** (LinkMetadata.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (LinkMetadata.CreateTime Get end)

                // *** End programmer edit section *** (LinkMetadata.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LinkMetadata.CreateTime Set start)

                // *** End programmer edit section *** (LinkMetadata.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (LinkMetadata.CreateTime Set end)

                // *** End programmer edit section *** (LinkMetadata.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (LinkMetadata.Creator CustomAttributes)

        // *** End programmer edit section *** (LinkMetadata.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (LinkMetadata.Creator Get start)

                // *** End programmer edit section *** (LinkMetadata.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (LinkMetadata.Creator Get end)

                // *** End programmer edit section *** (LinkMetadata.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LinkMetadata.Creator Set start)

                // *** End programmer edit section *** (LinkMetadata.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (LinkMetadata.Creator Set end)

                // *** End programmer edit section *** (LinkMetadata.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (LinkMetadata.EditTime CustomAttributes)

        // *** End programmer edit section *** (LinkMetadata.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (LinkMetadata.EditTime Get start)

                // *** End programmer edit section *** (LinkMetadata.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (LinkMetadata.EditTime Get end)

                // *** End programmer edit section *** (LinkMetadata.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LinkMetadata.EditTime Set start)

                // *** End programmer edit section *** (LinkMetadata.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (LinkMetadata.EditTime Set end)

                // *** End programmer edit section *** (LinkMetadata.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (LinkMetadata.Editor CustomAttributes)

        // *** End programmer edit section *** (LinkMetadata.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (LinkMetadata.Editor Get start)

                // *** End programmer edit section *** (LinkMetadata.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (LinkMetadata.Editor Get end)

                // *** End programmer edit section *** (LinkMetadata.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LinkMetadata.Editor Set start)

                // *** End programmer edit section *** (LinkMetadata.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (LinkMetadata.Editor Set end)

                // *** End programmer edit section *** (LinkMetadata.Editor Set end)
            }
        }
        
        /// <summary>
        /// LinkMetadata.
        /// </summary>
        // *** Start programmer edit section *** (LinkMetadata.MapObjectSetting CustomAttributes)

        // *** End programmer edit section *** (LinkMetadata.MapObjectSetting CustomAttributes)
        [PropertyStorage(new string[] {
                "MapObjectSetting"})]
        [NotNull()]
        public virtual NewPlatform.Flexberry.GIS.MapObjectSetting MapObjectSetting
        {
            get
            {
                // *** Start programmer edit section *** (LinkMetadata.MapObjectSetting Get start)

                // *** End programmer edit section *** (LinkMetadata.MapObjectSetting Get start)
                NewPlatform.Flexberry.GIS.MapObjectSetting result = this.fMapObjectSetting;
                // *** Start programmer edit section *** (LinkMetadata.MapObjectSetting Get end)

                // *** End programmer edit section *** (LinkMetadata.MapObjectSetting Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LinkMetadata.MapObjectSetting Set start)

                // *** End programmer edit section *** (LinkMetadata.MapObjectSetting Set start)
                this.fMapObjectSetting = value;
                // *** Start programmer edit section *** (LinkMetadata.MapObjectSetting Set end)

                // *** End programmer edit section *** (LinkMetadata.MapObjectSetting Set end)
            }
        }
        
        /// <summary>
        /// LinkMetadata.
        /// </summary>
        // *** Start programmer edit section *** (LinkMetadata.Parameters CustomAttributes)

        // *** End programmer edit section *** (LinkMetadata.Parameters CustomAttributes)
        public virtual NewPlatform.Flexberry.GIS.DetailArrayOfParameterMetadata Parameters
        {
            get
            {
                // *** Start programmer edit section *** (LinkMetadata.Parameters Get start)

                // *** End programmer edit section *** (LinkMetadata.Parameters Get start)
                if ((this.fParameters == null))
                {
                    this.fParameters = new NewPlatform.Flexberry.GIS.DetailArrayOfParameterMetadata(this);
                }
                NewPlatform.Flexberry.GIS.DetailArrayOfParameterMetadata result = this.fParameters;
                // *** Start programmer edit section *** (LinkMetadata.Parameters Get end)

                // *** End programmer edit section *** (LinkMetadata.Parameters Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LinkMetadata.Parameters Set start)

                // *** End programmer edit section *** (LinkMetadata.Parameters Set start)
                this.fParameters = value;
                // *** Start programmer edit section *** (LinkMetadata.Parameters Set end)

                // *** End programmer edit section *** (LinkMetadata.Parameters Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.GIS.LayerMetadata.
        /// </summary>
        // *** Start programmer edit section *** (LinkMetadata.Layer CustomAttributes)

        // *** End programmer edit section *** (LinkMetadata.Layer CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Layer"})]
        public virtual NewPlatform.Flexberry.GIS.LayerMetadata Layer
        {
            get
            {
                // *** Start programmer edit section *** (LinkMetadata.Layer Get start)

                // *** End programmer edit section *** (LinkMetadata.Layer Get start)
                NewPlatform.Flexberry.GIS.LayerMetadata result = this.fLayer;
                // *** Start programmer edit section *** (LinkMetadata.Layer Get end)

                // *** End programmer edit section *** (LinkMetadata.Layer Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LinkMetadata.Layer Set start)

                // *** End programmer edit section *** (LinkMetadata.Layer Set start)
                this.fLayer = value;
                // *** Start programmer edit section *** (LinkMetadata.Layer Set end)

                // *** End programmer edit section *** (LinkMetadata.Layer Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(NewPlatform.Flexberry.GIS.LinkMetadata));
                }
            }
            
            /// <summary>
            /// "LinkMetadataD" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LinkMetadataD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LinkMetadataD", typeof(NewPlatform.Flexberry.GIS.LinkMetadata));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of LinkMetadata.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfLinkMetadata CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfLinkMetadata CustomAttributes)
    public class DetailArrayOfLinkMetadata : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.GIS.DetailArrayOfLinkMetadata members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.GIS.DetailArrayOfLinkMetadata members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type LinkMetadata by index.
        /// </summary>
        /// <summary>
        /// Adds object with type LinkMetadata.
        /// </summary>
        public DetailArrayOfLinkMetadata(NewPlatform.Flexberry.GIS.LayerMetadata fLayerMetadata) : 
                base(typeof(LinkMetadata), ((ICSSoft.STORMNET.DataObject)(fLayerMetadata)))
        {
        }
        
        public NewPlatform.Flexberry.GIS.LinkMetadata this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.GIS.LinkMetadata)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.GIS.LinkMetadata dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
