//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.GIS
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// FavoriteFeatures.
    /// </summary>
    // *** Start programmer edit section *** (FavoriteFeatures CustomAttributes)

    // *** End programmer edit section *** (FavoriteFeatures CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "CreateTime",
            "Creator",
            "EditTime",
            "Editor",
            "ObjectKey",
            "ObjectLayerKey",
            "UserKey"})]
    public class FavoriteFeatures : ICSSoft.STORMNET.DataObject
    {
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private string fObjectKey;
        
        private string fObjectLayerKey;
        
        private string fUserKey;
        
        // *** Start programmer edit section *** (FavoriteFeatures CustomMembers)

        // *** End programmer edit section *** (FavoriteFeatures CustomMembers)

        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (FavoriteFeatures.CreateTime CustomAttributes)

        // *** End programmer edit section *** (FavoriteFeatures.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (FavoriteFeatures.CreateTime Get start)

                // *** End programmer edit section *** (FavoriteFeatures.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (FavoriteFeatures.CreateTime Get end)

                // *** End programmer edit section *** (FavoriteFeatures.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FavoriteFeatures.CreateTime Set start)

                // *** End programmer edit section *** (FavoriteFeatures.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (FavoriteFeatures.CreateTime Set end)

                // *** End programmer edit section *** (FavoriteFeatures.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (FavoriteFeatures.Creator CustomAttributes)

        // *** End programmer edit section *** (FavoriteFeatures.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (FavoriteFeatures.Creator Get start)

                // *** End programmer edit section *** (FavoriteFeatures.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (FavoriteFeatures.Creator Get end)

                // *** End programmer edit section *** (FavoriteFeatures.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FavoriteFeatures.Creator Set start)

                // *** End programmer edit section *** (FavoriteFeatures.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (FavoriteFeatures.Creator Set end)

                // *** End programmer edit section *** (FavoriteFeatures.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (FavoriteFeatures.EditTime CustomAttributes)

        // *** End programmer edit section *** (FavoriteFeatures.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (FavoriteFeatures.EditTime Get start)

                // *** End programmer edit section *** (FavoriteFeatures.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (FavoriteFeatures.EditTime Get end)

                // *** End programmer edit section *** (FavoriteFeatures.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FavoriteFeatures.EditTime Set start)

                // *** End programmer edit section *** (FavoriteFeatures.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (FavoriteFeatures.EditTime Set end)

                // *** End programmer edit section *** (FavoriteFeatures.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (FavoriteFeatures.Editor CustomAttributes)

        // *** End programmer edit section *** (FavoriteFeatures.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (FavoriteFeatures.Editor Get start)

                // *** End programmer edit section *** (FavoriteFeatures.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (FavoriteFeatures.Editor Get end)

                // *** End programmer edit section *** (FavoriteFeatures.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FavoriteFeatures.Editor Set start)

                // *** End programmer edit section *** (FavoriteFeatures.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (FavoriteFeatures.Editor Set end)

                // *** End programmer edit section *** (FavoriteFeatures.Editor Set end)
            }
        }
        
        /// <summary>
        /// Ключ объекта.
        /// </summary>
        // *** Start programmer edit section *** (FavoriteFeatures.ObjectKey CustomAttributes)

        // *** End programmer edit section *** (FavoriteFeatures.ObjectKey CustomAttributes)
        [StrLen(50)]
        [NotNull()]
        public virtual string ObjectKey
        {
            get
            {
                // *** Start programmer edit section *** (FavoriteFeatures.ObjectKey Get start)

                // *** End programmer edit section *** (FavoriteFeatures.ObjectKey Get start)
                string result = this.fObjectKey;
                // *** Start programmer edit section *** (FavoriteFeatures.ObjectKey Get end)

                // *** End programmer edit section *** (FavoriteFeatures.ObjectKey Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FavoriteFeatures.ObjectKey Set start)

                // *** End programmer edit section *** (FavoriteFeatures.ObjectKey Set start)
                this.fObjectKey = value;
                // *** Start programmer edit section *** (FavoriteFeatures.ObjectKey Set end)

                // *** End programmer edit section *** (FavoriteFeatures.ObjectKey Set end)
            }
        }
        
        /// <summary>
        /// Ключ слоя.
        /// </summary>
        // *** Start programmer edit section *** (FavoriteFeatures.ObjectLayerKey CustomAttributes)

        // *** End programmer edit section *** (FavoriteFeatures.ObjectLayerKey CustomAttributes)
        [StrLen(50)]
        [NotNull()]
        public virtual string ObjectLayerKey
        {
            get
            {
                // *** Start programmer edit section *** (FavoriteFeatures.ObjectLayerKey Get start)

                // *** End programmer edit section *** (FavoriteFeatures.ObjectLayerKey Get start)
                string result = this.fObjectLayerKey;
                // *** Start programmer edit section *** (FavoriteFeatures.ObjectLayerKey Get end)

                // *** End programmer edit section *** (FavoriteFeatures.ObjectLayerKey Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FavoriteFeatures.ObjectLayerKey Set start)

                // *** End programmer edit section *** (FavoriteFeatures.ObjectLayerKey Set start)
                this.fObjectLayerKey = value;
                // *** Start programmer edit section *** (FavoriteFeatures.ObjectLayerKey Set end)

                // *** End programmer edit section *** (FavoriteFeatures.ObjectLayerKey Set end)
            }
        }
        
        /// <summary>
        /// Ключ пользователя.
        /// </summary>
        // *** Start programmer edit section *** (FavoriteFeatures.UserKey CustomAttributes)

        // *** End programmer edit section *** (FavoriteFeatures.UserKey CustomAttributes)
        [StrLen(50)]
        [NotNull()]
        public virtual string UserKey
        {
            get
            {
                // *** Start programmer edit section *** (FavoriteFeatures.UserKey Get start)

                // *** End programmer edit section *** (FavoriteFeatures.UserKey Get start)
                string result = this.fUserKey;
                // *** Start programmer edit section *** (FavoriteFeatures.UserKey Get end)

                // *** End programmer edit section *** (FavoriteFeatures.UserKey Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FavoriteFeatures.UserKey Set start)

                // *** End programmer edit section *** (FavoriteFeatures.UserKey Set start)
                this.fUserKey = value;
                // *** Start programmer edit section *** (FavoriteFeatures.UserKey Set end)

                // *** End programmer edit section *** (FavoriteFeatures.UserKey Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(NewPlatform.Flexberry.GIS.FavoriteFeatures));
                }
            }
        }
    }
}
