//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.GIS
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// IPublicOwner.
    /// </summary>
    // *** Start programmer edit section *** (IPublicOwner CustomAttributes)

    // *** End programmer edit section *** (IPublicOwner CustomAttributes)
    public interface IPublicOwner
    {
        
        // *** Start programmer edit section *** (IPublicOwner CustomMembers)

        // *** End programmer edit section *** (IPublicOwner CustomMembers)

        
        /// <summary>
        /// Public.
        /// </summary>
        // *** Start programmer edit section *** (Public CustomAttributes)

        // *** End programmer edit section *** (Public CustomAttributes)
        bool Public
        {
            get;
            set;
        }
        
        /// <summary>
        /// Owner.
        /// </summary>
        // *** Start programmer edit section *** (Owner CustomAttributes)

        // *** End programmer edit section *** (Owner CustomAttributes)
        string Owner
        {
            get;
            set;
        }
    }
}
