//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.GIS
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// LinkParameter.
    /// </summary>
    // *** Start programmer edit section *** (LinkParameter CustomAttributes)

    // *** End programmer edit section *** (LinkParameter CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("LinkParameterD", new string[] {
            "ObjectField as \'Поле объекта\'",
            "LayerField as \'Поле слоя\'",
            "Expression as \'Выражение\'",
            "QueryKey as \'Ключ запроса\'",
            "LinkField as \'Ключ связи\'",
            "LayerLink as \'Связь\'"}, Hidden=new string[] {
            "Expression",
            "LinkField",
            "LayerLink"})]
    public class LinkParameter : ICSSoft.STORMNET.DataObject
    {
        
        private string fObjectField;
        
        private string fLayerField;
        
        private string fExpression;
        
        private string fQueryKey;
        
        private bool fLinkField = false;
        
        private NewPlatform.Flexberry.GIS.LayerLink fLayerLink;
        
        // *** Start programmer edit section *** (LinkParameter CustomMembers)

        // *** End programmer edit section *** (LinkParameter CustomMembers)

        
        /// <summary>
        /// ObjectField.
        /// </summary>
        // *** Start programmer edit section *** (LinkParameter.ObjectField CustomAttributes)

        // *** End programmer edit section *** (LinkParameter.ObjectField CustomAttributes)
        [StrLen(255)]
        public virtual string ObjectField
        {
            get
            {
                // *** Start programmer edit section *** (LinkParameter.ObjectField Get start)

                // *** End programmer edit section *** (LinkParameter.ObjectField Get start)
                string result = this.fObjectField;
                // *** Start programmer edit section *** (LinkParameter.ObjectField Get end)

                // *** End programmer edit section *** (LinkParameter.ObjectField Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LinkParameter.ObjectField Set start)

                // *** End programmer edit section *** (LinkParameter.ObjectField Set start)
                this.fObjectField = value;
                // *** Start programmer edit section *** (LinkParameter.ObjectField Set end)

                // *** End programmer edit section *** (LinkParameter.ObjectField Set end)
            }
        }
        
        /// <summary>
        /// LayerField.
        /// </summary>
        // *** Start programmer edit section *** (LinkParameter.LayerField CustomAttributes)

        // *** End programmer edit section *** (LinkParameter.LayerField CustomAttributes)
        [StrLen(255)]
        public virtual string LayerField
        {
            get
            {
                // *** Start programmer edit section *** (LinkParameter.LayerField Get start)

                // *** End programmer edit section *** (LinkParameter.LayerField Get start)
                string result = this.fLayerField;
                // *** Start programmer edit section *** (LinkParameter.LayerField Get end)

                // *** End programmer edit section *** (LinkParameter.LayerField Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LinkParameter.LayerField Set start)

                // *** End programmer edit section *** (LinkParameter.LayerField Set start)
                this.fLayerField = value;
                // *** Start programmer edit section *** (LinkParameter.LayerField Set end)

                // *** End programmer edit section *** (LinkParameter.LayerField Set end)
            }
        }
        
        /// <summary>
        /// Expression.
        /// </summary>
        // *** Start programmer edit section *** (LinkParameter.Expression CustomAttributes)

        // *** End programmer edit section *** (LinkParameter.Expression CustomAttributes)
        [StrLen(255)]
        public virtual string Expression
        {
            get
            {
                // *** Start programmer edit section *** (LinkParameter.Expression Get start)

                // *** End programmer edit section *** (LinkParameter.Expression Get start)
                string result = this.fExpression;
                // *** Start programmer edit section *** (LinkParameter.Expression Get end)

                // *** End programmer edit section *** (LinkParameter.Expression Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LinkParameter.Expression Set start)

                // *** End programmer edit section *** (LinkParameter.Expression Set start)
                this.fExpression = value;
                // *** Start programmer edit section *** (LinkParameter.Expression Set end)

                // *** End programmer edit section *** (LinkParameter.Expression Set end)
            }
        }
        
        /// <summary>
        /// QueryKey.
        /// </summary>
        // *** Start programmer edit section *** (LinkParameter.QueryKey CustomAttributes)

        // *** End programmer edit section *** (LinkParameter.QueryKey CustomAttributes)
        [StrLen(255)]
        public virtual string QueryKey
        {
            get
            {
                // *** Start programmer edit section *** (LinkParameter.QueryKey Get start)

                // *** End programmer edit section *** (LinkParameter.QueryKey Get start)
                string result = this.fQueryKey;
                // *** Start programmer edit section *** (LinkParameter.QueryKey Get end)

                // *** End programmer edit section *** (LinkParameter.QueryKey Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LinkParameter.QueryKey Set start)

                // *** End programmer edit section *** (LinkParameter.QueryKey Set start)
                this.fQueryKey = value;
                // *** Start programmer edit section *** (LinkParameter.QueryKey Set end)

                // *** End programmer edit section *** (LinkParameter.QueryKey Set end)
            }
        }
        
        /// <summary>
        /// LinkField.
        /// </summary>
        // *** Start programmer edit section *** (LinkParameter.LinkField CustomAttributes)

        // *** End programmer edit section *** (LinkParameter.LinkField CustomAttributes)
        public virtual bool LinkField
        {
            get
            {
                // *** Start programmer edit section *** (LinkParameter.LinkField Get start)

                // *** End programmer edit section *** (LinkParameter.LinkField Get start)
                bool result = this.fLinkField;
                // *** Start programmer edit section *** (LinkParameter.LinkField Get end)

                // *** End programmer edit section *** (LinkParameter.LinkField Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LinkParameter.LinkField Set start)

                // *** End programmer edit section *** (LinkParameter.LinkField Set start)
                this.fLinkField = value;
                // *** Start programmer edit section *** (LinkParameter.LinkField Set end)

                // *** End programmer edit section *** (LinkParameter.LinkField Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.GIS.LayerLink.
        /// </summary>
        // *** Start programmer edit section *** (LinkParameter.LayerLink CustomAttributes)

        // *** End programmer edit section *** (LinkParameter.LayerLink CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "LayerLink"})]
        public virtual NewPlatform.Flexberry.GIS.LayerLink LayerLink
        {
            get
            {
                // *** Start programmer edit section *** (LinkParameter.LayerLink Get start)

                // *** End programmer edit section *** (LinkParameter.LayerLink Get start)
                NewPlatform.Flexberry.GIS.LayerLink result = this.fLayerLink;
                // *** Start programmer edit section *** (LinkParameter.LayerLink Get end)

                // *** End programmer edit section *** (LinkParameter.LayerLink Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LinkParameter.LayerLink Set start)

                // *** End programmer edit section *** (LinkParameter.LayerLink Set start)
                this.fLayerLink = value;
                // *** Start programmer edit section *** (LinkParameter.LayerLink Set end)

                // *** End programmer edit section *** (LinkParameter.LayerLink Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "LinkParameterD" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LinkParameterD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LinkParameterD", typeof(NewPlatform.Flexberry.GIS.LinkParameter));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of LinkParameter.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfLinkParameter CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfLinkParameter CustomAttributes)
    public class DetailArrayOfLinkParameter : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.GIS.DetailArrayOfLinkParameter members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.GIS.DetailArrayOfLinkParameter members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type LinkParameter by index.
        /// </summary>
        /// <summary>
        /// Adds object with type LinkParameter.
        /// </summary>
        public DetailArrayOfLinkParameter(NewPlatform.Flexberry.GIS.LayerLink fLayerLink) : 
                base(typeof(LinkParameter), ((ICSSoft.STORMNET.DataObject)(fLayerLink)))
        {
        }
        
        public NewPlatform.Flexberry.GIS.LinkParameter this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.GIS.LinkParameter)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.GIS.LinkParameter dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
