//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.GIS
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Map layer.
    /// </summary>
    // *** Start programmer edit section *** (MapLayer CustomAttributes)

    // *** End programmer edit section *** (MapLayer CustomAttributes)
    [AutoAltered()]
    [Caption("Map layer")]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "Name as \'Наименование\'",
            "Creator as \'Создатель\'",
            "CreateTime as \'Время создания\'",
            "Editor as \'Редактор\'",
            "EditTime as \'Время редактирования\'"})]
    [View("MapLayerD", new string[] {
            "Name as \'Наименование\'",
            "Description as \'Описание\'",
            "KeyWords as \'Ключевые слова\'",
            "Index as \'Индекс\'",
            "Visibility as \'Видимость\'",
            "Type as \'Тип\'",
            "Settings as \'Настройки\'",
            "Scale as \'Масштаб\'",
            "CoordinateReferenceSystem as \'Система координат\'",
            "BoundingBox as \'Граница\'",
            "Parent as \'Родитель\'",
            "Map as \'Карта\'"}, Hidden=new string[] {
            "Parent",
            "Map"})]
    [AssociatedDetailViewAttribute("MapLayerD", "LayerLink", "LayerLinkD", true, "", "", true, new string[] {
            ""})]
    [View("MapLayerE", new string[] {
            "Name as \'Наименование\'",
            "Description as \'Описание\'",
            "KeyWords as \'Ключевые слова\'",
            "Index as \'Индекс\'",
            "Visibility as \'Видимость\'",
            "Type as \'Тип\'",
            "Settings as \'Настройки\'",
            "Scale as \'Масштаб\'",
            "CoordinateReferenceSystem as \'Система координат\'",
            "BoundingBox as \'Граница\'",
            "Parent as \'Родитель\'",
            "Map as \'Карта\'"})]
    [AssociatedDetailViewAttribute("MapLayerE", "LayerLink", "LayerLinkD", true, "", "", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("MapLayerE", "Parent", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("MapLayerE", "Map", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("MapLayerL", new string[] {
            "Name as \'Наименование\'",
            "Description as \'Описание\'",
            "Type as \'Тип\'",
            "Parent.Name as \'Родитель\'"})]
    public class MapLayer : ICSSoft.STORMNET.DataObject, NewPlatform.Flexberry.GIS.IPublicOwner, IDataObjectWithAuditFields
    {
        
        private string fName;
        
        private string fDescription;
        
        private string fKeyWords;
        
        private int fIndex;
        
        private bool fVisibility = true;
        
        private string fType;
        
        private string fSettings;
        
        private int fScale;
        
        private string fCoordinateReferenceSystem;
        
        private Microsoft.Spatial.Geography fBoundingBox;
        
        private bool fPublic;
        
        private string fOwner;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private NewPlatform.Flexberry.GIS.MapLayer fParent;
        
        private NewPlatform.Flexberry.GIS.DetailArrayOfLayerLink fLayerLink;
        
        private NewPlatform.Flexberry.GIS.Map fMap;
        
        // *** Start programmer edit section *** (MapLayer CustomMembers)

        // *** End programmer edit section *** (MapLayer CustomMembers)

        
        /// <summary>
        /// Наименование слоя.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.Name CustomAttributes)

        // *** End programmer edit section *** (MapLayer.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.Name Get start)

                // *** End programmer edit section *** (MapLayer.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (MapLayer.Name Get end)

                // *** End programmer edit section *** (MapLayer.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.Name Set start)

                // *** End programmer edit section *** (MapLayer.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (MapLayer.Name Set end)

                // *** End programmer edit section *** (MapLayer.Name Set end)
            }
        }
        
        /// <summary>
        /// Описание слоя.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.Description CustomAttributes)

        // *** End programmer edit section *** (MapLayer.Description CustomAttributes)
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.Description Get start)

                // *** End programmer edit section *** (MapLayer.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (MapLayer.Description Get end)

                // *** End programmer edit section *** (MapLayer.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.Description Set start)

                // *** End programmer edit section *** (MapLayer.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (MapLayer.Description Set end)

                // *** End programmer edit section *** (MapLayer.Description Set end)
            }
        }
        
        /// <summary>
        /// Ключевые слова имеющие отношение к слою или его тематике.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.KeyWords CustomAttributes)

        // *** End programmer edit section *** (MapLayer.KeyWords CustomAttributes)
        public virtual string KeyWords
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.KeyWords Get start)

                // *** End programmer edit section *** (MapLayer.KeyWords Get start)
                string result = this.fKeyWords;
                // *** Start programmer edit section *** (MapLayer.KeyWords Get end)

                // *** End programmer edit section *** (MapLayer.KeyWords Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.KeyWords Set start)

                // *** End programmer edit section *** (MapLayer.KeyWords Set start)
                this.fKeyWords = value;
                // *** Start programmer edit section *** (MapLayer.KeyWords Set end)

                // *** End programmer edit section *** (MapLayer.KeyWords Set end)
            }
        }
        
        /// <summary>
        /// Вычислимое поле для полнотекстового поиска ключевым словам, наименованию и описанию карты.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.AnyText CustomAttributes)

        // *** End programmer edit section *** (MapLayer.AnyText CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        [DataServiceExpression(typeof(ICSSoft.STORMNET.Business.SQLDataService), "ISNULL(@Name@, \'\') + \' \' + ISNULL(@Description@, \'\') + \' \' + REPLACE(ISNULL(@KeyW" +
            "ords@, \'\'), \',\', \' \')")]
        [DataServiceExpression(typeof(ICSSoft.STORMNET.Business.MSSQLDataService), "ISNULL(@Name@, \'\') + \' \' + ISNULL(@Description@, \'\') + \' \' + REPLACE(ISNULL(@KeyW" +
            "ords@, \'\'), \',\', \' \')")]
        [DataServiceExpression(typeof(ICSSoft.STORMNET.Business.PostgresDataService), "COALESCE(@Name@, \'\') || \' \' || COALESCE(@Description@, \'\') || \' \' || REPLACE(COAL" +
            "ESCE(@KeyWords@, \'\'), \',\', \' \')")]
        [DataServiceExpression(typeof(ICSSoft.STORMNET.Business.OracleDataService), "COALESCE(@Name@, \\\'\\\') || \\\' \\\' || COALESCE(@Description@, \\\'\\\') || \\\' \\\' || REPL" +
            "ACE(COALESCE(@KeyWords@, \\\'\\\'), \\\',\\\', \\\' \\\')")]
        public virtual string AnyText
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.AnyText Get)
                return null;
                // *** End programmer edit section *** (MapLayer.AnyText Get)
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.AnyText Set)

                // *** End programmer edit section *** (MapLayer.AnyText Set)
            }
        }
        
        /// <summary>
        /// Место слоя в иерархии (по сути z-index).
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.Index CustomAttributes)

        // *** End programmer edit section *** (MapLayer.Index CustomAttributes)
        public virtual int Index
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.Index Get start)

                // *** End programmer edit section *** (MapLayer.Index Get start)
                int result = this.fIndex;
                // *** Start programmer edit section *** (MapLayer.Index Get end)

                // *** End programmer edit section *** (MapLayer.Index Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.Index Set start)

                // *** End programmer edit section *** (MapLayer.Index Set start)
                this.fIndex = value;
                // *** Start programmer edit section *** (MapLayer.Index Set end)

                // *** End programmer edit section *** (MapLayer.Index Set end)
            }
        }
        
        /// <summary>
        /// Видимость слоя.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.Visibility CustomAttributes)

        // *** End programmer edit section *** (MapLayer.Visibility CustomAttributes)
        public virtual bool Visibility
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.Visibility Get start)

                // *** End programmer edit section *** (MapLayer.Visibility Get start)
                bool result = this.fVisibility;
                // *** Start programmer edit section *** (MapLayer.Visibility Get end)

                // *** End programmer edit section *** (MapLayer.Visibility Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.Visibility Set start)

                // *** End programmer edit section *** (MapLayer.Visibility Set start)
                this.fVisibility = value;
                // *** Start programmer edit section *** (MapLayer.Visibility Set end)

                // *** End programmer edit section *** (MapLayer.Visibility Set end)
            }
        }
        
        /// <summary>
        /// Тип слоя.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.Type CustomAttributes)

        // *** End programmer edit section *** (MapLayer.Type CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Type
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.Type Get start)

                // *** End programmer edit section *** (MapLayer.Type Get start)
                string result = this.fType;
                // *** Start programmer edit section *** (MapLayer.Type Get end)

                // *** End programmer edit section *** (MapLayer.Type Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.Type Set start)

                // *** End programmer edit section *** (MapLayer.Type Set start)
                this.fType = value;
                // *** Start programmer edit section *** (MapLayer.Type Set end)

                // *** End programmer edit section *** (MapLayer.Type Set end)
            }
        }
        
        /// <summary>
        /// Настройки слоя.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.Settings CustomAttributes)

        // *** End programmer edit section *** (MapLayer.Settings CustomAttributes)
        public virtual string Settings
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.Settings Get start)

                // *** End programmer edit section *** (MapLayer.Settings Get start)
                string result = this.fSettings;
                // *** Start programmer edit section *** (MapLayer.Settings Get end)

                // *** End programmer edit section *** (MapLayer.Settings Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.Settings Set start)

                // *** End programmer edit section *** (MapLayer.Settings Set start)
                this.fSettings = value;
                // *** Start programmer edit section *** (MapLayer.Settings Set end)

                // *** End programmer edit section *** (MapLayer.Settings Set end)
            }
        }
        
        /// <summary>
        /// Масштаб или точность данных слоя.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.Scale CustomAttributes)

        // *** End programmer edit section *** (MapLayer.Scale CustomAttributes)
        public virtual int Scale
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.Scale Get start)

                // *** End programmer edit section *** (MapLayer.Scale Get start)
                int result = this.fScale;
                // *** Start programmer edit section *** (MapLayer.Scale Get end)

                // *** End programmer edit section *** (MapLayer.Scale Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.Scale Set start)

                // *** End programmer edit section *** (MapLayer.Scale Set start)
                this.fScale = value;
                // *** Start programmer edit section *** (MapLayer.Scale Set end)

                // *** End programmer edit section *** (MapLayer.Scale Set end)
            }
        }
        
        /// <summary>
        /// Система координат слоя.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.CoordinateReferenceSystem CustomAttributes)

        // *** End programmer edit section *** (MapLayer.CoordinateReferenceSystem CustomAttributes)
        [StrLen(255)]
        public virtual string CoordinateReferenceSystem
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.CoordinateReferenceSystem Get start)

                // *** End programmer edit section *** (MapLayer.CoordinateReferenceSystem Get start)
                string result = this.fCoordinateReferenceSystem;
                // *** Start programmer edit section *** (MapLayer.CoordinateReferenceSystem Get end)

                // *** End programmer edit section *** (MapLayer.CoordinateReferenceSystem Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.CoordinateReferenceSystem Set start)

                // *** End programmer edit section *** (MapLayer.CoordinateReferenceSystem Set start)
                this.fCoordinateReferenceSystem = value;
                // *** Start programmer edit section *** (MapLayer.CoordinateReferenceSystem Set end)

                // *** End programmer edit section *** (MapLayer.CoordinateReferenceSystem Set end)
            }
        }
        
        /// <summary>
        /// Границы слоя.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.BoundingBox CustomAttributes)

        // *** End programmer edit section *** (MapLayer.BoundingBox CustomAttributes)
        public virtual Microsoft.Spatial.Geography BoundingBox
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.BoundingBox Get start)

                // *** End programmer edit section *** (MapLayer.BoundingBox Get start)
                Microsoft.Spatial.Geography result = this.fBoundingBox;
                // *** Start programmer edit section *** (MapLayer.BoundingBox Get end)

                // *** End programmer edit section *** (MapLayer.BoundingBox Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.BoundingBox Set start)

                // *** End programmer edit section *** (MapLayer.BoundingBox Set start)
                this.fBoundingBox = value;
                // *** Start programmer edit section *** (MapLayer.BoundingBox Set end)

                // *** End programmer edit section *** (MapLayer.BoundingBox Set end)
            }
        }
        
        /// <summary>
        /// Public.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.Public CustomAttributes)

        // *** End programmer edit section *** (MapLayer.Public CustomAttributes)
        public virtual bool Public
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.Public Get start)

                // *** End programmer edit section *** (MapLayer.Public Get start)
                bool result = this.fPublic;
                // *** Start programmer edit section *** (MapLayer.Public Get end)

                // *** End programmer edit section *** (MapLayer.Public Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.Public Set start)

                // *** End programmer edit section *** (MapLayer.Public Set start)
                this.fPublic = value;
                // *** Start programmer edit section *** (MapLayer.Public Set end)

                // *** End programmer edit section *** (MapLayer.Public Set end)
            }
        }
        
        /// <summary>
        /// Owner.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.Owner CustomAttributes)

        // *** End programmer edit section *** (MapLayer.Owner CustomAttributes)
        [StrLen(255)]
        public virtual string Owner
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.Owner Get start)

                // *** End programmer edit section *** (MapLayer.Owner Get start)
                string result = this.fOwner;
                // *** Start programmer edit section *** (MapLayer.Owner Get end)

                // *** End programmer edit section *** (MapLayer.Owner Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.Owner Set start)

                // *** End programmer edit section *** (MapLayer.Owner Set start)
                this.fOwner = value;
                // *** Start programmer edit section *** (MapLayer.Owner Set end)

                // *** End programmer edit section *** (MapLayer.Owner Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.CreateTime CustomAttributes)

        // *** End programmer edit section *** (MapLayer.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.CreateTime Get start)

                // *** End programmer edit section *** (MapLayer.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (MapLayer.CreateTime Get end)

                // *** End programmer edit section *** (MapLayer.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.CreateTime Set start)

                // *** End programmer edit section *** (MapLayer.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (MapLayer.CreateTime Set end)

                // *** End programmer edit section *** (MapLayer.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.Creator CustomAttributes)

        // *** End programmer edit section *** (MapLayer.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.Creator Get start)

                // *** End programmer edit section *** (MapLayer.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (MapLayer.Creator Get end)

                // *** End programmer edit section *** (MapLayer.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.Creator Set start)

                // *** End programmer edit section *** (MapLayer.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (MapLayer.Creator Set end)

                // *** End programmer edit section *** (MapLayer.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.EditTime CustomAttributes)

        // *** End programmer edit section *** (MapLayer.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.EditTime Get start)

                // *** End programmer edit section *** (MapLayer.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (MapLayer.EditTime Get end)

                // *** End programmer edit section *** (MapLayer.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.EditTime Set start)

                // *** End programmer edit section *** (MapLayer.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (MapLayer.EditTime Set end)

                // *** End programmer edit section *** (MapLayer.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.Editor CustomAttributes)

        // *** End programmer edit section *** (MapLayer.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.Editor Get start)

                // *** End programmer edit section *** (MapLayer.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (MapLayer.Editor Get end)

                // *** End programmer edit section *** (MapLayer.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.Editor Set start)

                // *** End programmer edit section *** (MapLayer.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (MapLayer.Editor Set end)

                // *** End programmer edit section *** (MapLayer.Editor Set end)
            }
        }
        
        /// <summary>
        /// Map layer.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.Parent CustomAttributes)

        // *** End programmer edit section *** (MapLayer.Parent CustomAttributes)
        [PropertyStorage(new string[] {
                "Parent"})]
        public virtual NewPlatform.Flexberry.GIS.MapLayer Parent
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.Parent Get start)

                // *** End programmer edit section *** (MapLayer.Parent Get start)
                NewPlatform.Flexberry.GIS.MapLayer result = this.fParent;
                // *** Start programmer edit section *** (MapLayer.Parent Get end)

                // *** End programmer edit section *** (MapLayer.Parent Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.Parent Set start)

                // *** End programmer edit section *** (MapLayer.Parent Set start)
                this.fParent = value;
                // *** Start programmer edit section *** (MapLayer.Parent Set end)

                // *** End programmer edit section *** (MapLayer.Parent Set end)
            }
        }
        
        /// <summary>
        /// Map layer.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.LayerLink CustomAttributes)

        // *** End programmer edit section *** (MapLayer.LayerLink CustomAttributes)
        public virtual NewPlatform.Flexberry.GIS.DetailArrayOfLayerLink LayerLink
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.LayerLink Get start)

                // *** End programmer edit section *** (MapLayer.LayerLink Get start)
                if ((this.fLayerLink == null))
                {
                    this.fLayerLink = new NewPlatform.Flexberry.GIS.DetailArrayOfLayerLink(this);
                }
                NewPlatform.Flexberry.GIS.DetailArrayOfLayerLink result = this.fLayerLink;
                // *** Start programmer edit section *** (MapLayer.LayerLink Get end)

                // *** End programmer edit section *** (MapLayer.LayerLink Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.LayerLink Set start)

                // *** End programmer edit section *** (MapLayer.LayerLink Set start)
                this.fLayerLink = value;
                // *** Start programmer edit section *** (MapLayer.LayerLink Set end)

                // *** End programmer edit section *** (MapLayer.LayerLink Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.GIS.Map.
        /// </summary>
        // *** Start programmer edit section *** (MapLayer.Map CustomAttributes)

        // *** End programmer edit section *** (MapLayer.Map CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Map"})]
        public virtual NewPlatform.Flexberry.GIS.Map Map
        {
            get
            {
                // *** Start programmer edit section *** (MapLayer.Map Get start)

                // *** End programmer edit section *** (MapLayer.Map Get start)
                NewPlatform.Flexberry.GIS.Map result = this.fMap;
                // *** Start programmer edit section *** (MapLayer.Map Get end)

                // *** End programmer edit section *** (MapLayer.Map Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MapLayer.Map Set start)

                // *** End programmer edit section *** (MapLayer.Map Set start)
                this.fMap = value;
                // *** Start programmer edit section *** (MapLayer.Map Set end)

                // *** End programmer edit section *** (MapLayer.Map Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// Представление для аудита.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(NewPlatform.Flexberry.GIS.MapLayer));
                }
            }
            
            /// <summary>
            /// Представление для форм редактирования агрегатора.
            /// </summary>
            public static ICSSoft.STORMNET.View MapLayerD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MapLayerD", typeof(NewPlatform.Flexberry.GIS.MapLayer));
                }
            }
            
            /// <summary>
            /// Представление для форм редактирования.
            /// </summary>
            public static ICSSoft.STORMNET.View MapLayerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MapLayerE", typeof(NewPlatform.Flexberry.GIS.MapLayer));
                }
            }
            
            /// <summary>
            /// Представление для списковых форм.
            /// </summary>
            public static ICSSoft.STORMNET.View MapLayerL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MapLayerL", typeof(NewPlatform.Flexberry.GIS.MapLayer));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of MapLayer.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfMapLayer CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfMapLayer CustomAttributes)
    public class DetailArrayOfMapLayer : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.GIS.DetailArrayOfMapLayer members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.GIS.DetailArrayOfMapLayer members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type MapLayer by index.
        /// </summary>
        /// <summary>
        /// Adds object with type MapLayer.
        /// </summary>
        public DetailArrayOfMapLayer(NewPlatform.Flexberry.GIS.Map fMap) : 
                base(typeof(MapLayer), ((ICSSoft.STORMNET.DataObject)(fMap)))
        {
        }
        
        public NewPlatform.Flexberry.GIS.MapLayer this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.GIS.MapLayer)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.GIS.MapLayer dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
