//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.GIS
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ParameterMetadata.
    /// </summary>
    // *** Start programmer edit section *** (ParameterMetadata CustomAttributes)

    // *** End programmer edit section *** (ParameterMetadata CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "ObjectField as \'Поле объекта\'",
            "LayerField as \'Поле слоя\'",
            "Expression as \'Выражение\'",
            "QueryKey as \'Ключ запроса\'",
            "LinkField as \'Поле связи\'",
            "LayerLink as \'Связь\'"})]
    [View("ParameterMetadataD", new string[] {
            "ObjectField as \'Поле объекта\'",
            "LayerField as \'Поле слоя\'",
            "Expression as \'Выражение\'",
            "QueryKey as \'Ключ запроса\'",
            "LinkField as \'Поле связи\'",
            "LayerLink as \'Связь\'"}, Hidden=new string[] {
            "LayerLink"})]
    public class ParameterMetadata : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fObjectField;
        
        private string fLayerField;
        
        private string fExpression;
        
        private string fQueryKey;
        
        private bool fLinkField = false;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private NewPlatform.Flexberry.GIS.LinkMetadata fLayerLink;
        
        // *** Start programmer edit section *** (ParameterMetadata CustomMembers)

        // *** End programmer edit section *** (ParameterMetadata CustomMembers)

        
        /// <summary>
        /// ObjectField.
        /// </summary>
        // *** Start programmer edit section *** (ParameterMetadata.ObjectField CustomAttributes)

        // *** End programmer edit section *** (ParameterMetadata.ObjectField CustomAttributes)
        [StrLen(255)]
        public virtual string ObjectField
        {
            get
            {
                // *** Start programmer edit section *** (ParameterMetadata.ObjectField Get start)

                // *** End programmer edit section *** (ParameterMetadata.ObjectField Get start)
                string result = this.fObjectField;
                // *** Start programmer edit section *** (ParameterMetadata.ObjectField Get end)

                // *** End programmer edit section *** (ParameterMetadata.ObjectField Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ParameterMetadata.ObjectField Set start)

                // *** End programmer edit section *** (ParameterMetadata.ObjectField Set start)
                this.fObjectField = value;
                // *** Start programmer edit section *** (ParameterMetadata.ObjectField Set end)

                // *** End programmer edit section *** (ParameterMetadata.ObjectField Set end)
            }
        }
        
        /// <summary>
        /// LayerField.
        /// </summary>
        // *** Start programmer edit section *** (ParameterMetadata.LayerField CustomAttributes)

        // *** End programmer edit section *** (ParameterMetadata.LayerField CustomAttributes)
        [StrLen(255)]
        public virtual string LayerField
        {
            get
            {
                // *** Start programmer edit section *** (ParameterMetadata.LayerField Get start)

                // *** End programmer edit section *** (ParameterMetadata.LayerField Get start)
                string result = this.fLayerField;
                // *** Start programmer edit section *** (ParameterMetadata.LayerField Get end)

                // *** End programmer edit section *** (ParameterMetadata.LayerField Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ParameterMetadata.LayerField Set start)

                // *** End programmer edit section *** (ParameterMetadata.LayerField Set start)
                this.fLayerField = value;
                // *** Start programmer edit section *** (ParameterMetadata.LayerField Set end)

                // *** End programmer edit section *** (ParameterMetadata.LayerField Set end)
            }
        }
        
        /// <summary>
        /// Expression.
        /// </summary>
        // *** Start programmer edit section *** (ParameterMetadata.Expression CustomAttributes)

        // *** End programmer edit section *** (ParameterMetadata.Expression CustomAttributes)
        [StrLen(255)]
        public virtual string Expression
        {
            get
            {
                // *** Start programmer edit section *** (ParameterMetadata.Expression Get start)

                // *** End programmer edit section *** (ParameterMetadata.Expression Get start)
                string result = this.fExpression;
                // *** Start programmer edit section *** (ParameterMetadata.Expression Get end)

                // *** End programmer edit section *** (ParameterMetadata.Expression Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ParameterMetadata.Expression Set start)

                // *** End programmer edit section *** (ParameterMetadata.Expression Set start)
                this.fExpression = value;
                // *** Start programmer edit section *** (ParameterMetadata.Expression Set end)

                // *** End programmer edit section *** (ParameterMetadata.Expression Set end)
            }
        }
        
        /// <summary>
        /// QueryKey.
        /// </summary>
        // *** Start programmer edit section *** (ParameterMetadata.QueryKey CustomAttributes)

        // *** End programmer edit section *** (ParameterMetadata.QueryKey CustomAttributes)
        [StrLen(255)]
        public virtual string QueryKey
        {
            get
            {
                // *** Start programmer edit section *** (ParameterMetadata.QueryKey Get start)

                // *** End programmer edit section *** (ParameterMetadata.QueryKey Get start)
                string result = this.fQueryKey;
                // *** Start programmer edit section *** (ParameterMetadata.QueryKey Get end)

                // *** End programmer edit section *** (ParameterMetadata.QueryKey Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ParameterMetadata.QueryKey Set start)

                // *** End programmer edit section *** (ParameterMetadata.QueryKey Set start)
                this.fQueryKey = value;
                // *** Start programmer edit section *** (ParameterMetadata.QueryKey Set end)

                // *** End programmer edit section *** (ParameterMetadata.QueryKey Set end)
            }
        }
        
        /// <summary>
        /// LinkField.
        /// </summary>
        // *** Start programmer edit section *** (ParameterMetadata.LinkField CustomAttributes)

        // *** End programmer edit section *** (ParameterMetadata.LinkField CustomAttributes)
        public virtual bool LinkField
        {
            get
            {
                // *** Start programmer edit section *** (ParameterMetadata.LinkField Get start)

                // *** End programmer edit section *** (ParameterMetadata.LinkField Get start)
                bool result = this.fLinkField;
                // *** Start programmer edit section *** (ParameterMetadata.LinkField Get end)

                // *** End programmer edit section *** (ParameterMetadata.LinkField Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ParameterMetadata.LinkField Set start)

                // *** End programmer edit section *** (ParameterMetadata.LinkField Set start)
                this.fLinkField = value;
                // *** Start programmer edit section *** (ParameterMetadata.LinkField Set end)

                // *** End programmer edit section *** (ParameterMetadata.LinkField Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (ParameterMetadata.CreateTime CustomAttributes)

        // *** End programmer edit section *** (ParameterMetadata.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (ParameterMetadata.CreateTime Get start)

                // *** End programmer edit section *** (ParameterMetadata.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (ParameterMetadata.CreateTime Get end)

                // *** End programmer edit section *** (ParameterMetadata.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ParameterMetadata.CreateTime Set start)

                // *** End programmer edit section *** (ParameterMetadata.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (ParameterMetadata.CreateTime Set end)

                // *** End programmer edit section *** (ParameterMetadata.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (ParameterMetadata.Creator CustomAttributes)

        // *** End programmer edit section *** (ParameterMetadata.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (ParameterMetadata.Creator Get start)

                // *** End programmer edit section *** (ParameterMetadata.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (ParameterMetadata.Creator Get end)

                // *** End programmer edit section *** (ParameterMetadata.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ParameterMetadata.Creator Set start)

                // *** End programmer edit section *** (ParameterMetadata.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (ParameterMetadata.Creator Set end)

                // *** End programmer edit section *** (ParameterMetadata.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (ParameterMetadata.EditTime CustomAttributes)

        // *** End programmer edit section *** (ParameterMetadata.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (ParameterMetadata.EditTime Get start)

                // *** End programmer edit section *** (ParameterMetadata.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (ParameterMetadata.EditTime Get end)

                // *** End programmer edit section *** (ParameterMetadata.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ParameterMetadata.EditTime Set start)

                // *** End programmer edit section *** (ParameterMetadata.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (ParameterMetadata.EditTime Set end)

                // *** End programmer edit section *** (ParameterMetadata.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (ParameterMetadata.Editor CustomAttributes)

        // *** End programmer edit section *** (ParameterMetadata.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (ParameterMetadata.Editor Get start)

                // *** End programmer edit section *** (ParameterMetadata.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (ParameterMetadata.Editor Get end)

                // *** End programmer edit section *** (ParameterMetadata.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ParameterMetadata.Editor Set start)

                // *** End programmer edit section *** (ParameterMetadata.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (ParameterMetadata.Editor Set end)

                // *** End programmer edit section *** (ParameterMetadata.Editor Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.GIS.LinkMetadata.
        /// </summary>
        // *** Start programmer edit section *** (ParameterMetadata.LayerLink CustomAttributes)

        // *** End programmer edit section *** (ParameterMetadata.LayerLink CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "LayerLink"})]
        public virtual NewPlatform.Flexberry.GIS.LinkMetadata LayerLink
        {
            get
            {
                // *** Start programmer edit section *** (ParameterMetadata.LayerLink Get start)

                // *** End programmer edit section *** (ParameterMetadata.LayerLink Get start)
                NewPlatform.Flexberry.GIS.LinkMetadata result = this.fLayerLink;
                // *** Start programmer edit section *** (ParameterMetadata.LayerLink Get end)

                // *** End programmer edit section *** (ParameterMetadata.LayerLink Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ParameterMetadata.LayerLink Set start)

                // *** End programmer edit section *** (ParameterMetadata.LayerLink Set start)
                this.fLayerLink = value;
                // *** Start programmer edit section *** (ParameterMetadata.LayerLink Set end)

                // *** End programmer edit section *** (ParameterMetadata.LayerLink Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(NewPlatform.Flexberry.GIS.ParameterMetadata));
                }
            }
            
            /// <summary>
            /// "ParameterMetadataD" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ParameterMetadataD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ParameterMetadataD", typeof(NewPlatform.Flexberry.GIS.ParameterMetadata));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of ParameterMetadata.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfParameterMetadata CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfParameterMetadata CustomAttributes)
    public class DetailArrayOfParameterMetadata : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.GIS.DetailArrayOfParameterMetadata members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.GIS.DetailArrayOfParameterMetadata members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ParameterMetadata by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ParameterMetadata.
        /// </summary>
        public DetailArrayOfParameterMetadata(NewPlatform.Flexberry.GIS.LinkMetadata fLinkMetadata) : 
                base(typeof(ParameterMetadata), ((ICSSoft.STORMNET.DataObject)(fLinkMetadata)))
        {
        }
        
        public NewPlatform.Flexberry.GIS.ParameterMetadata this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.GIS.ParameterMetadata)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.GIS.ParameterMetadata dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
