//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.GIS
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// DataLinkParameter.
    /// </summary>
    // *** Start programmer edit section *** (DataLinkParameter CustomAttributes)

    // *** End programmer edit section *** (DataLinkParameter CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("DataLinkParameterD", new string[] {
            "Link",
            "LinkField as \'Поле для связи\'",
            "ObjectField as \'Поле в объекте\'",
            "LayerField as \'Поле в таблице геоданных\'",
            "Expression as \'SQL выражение\'"}, Hidden=new string[] {
            "Link"})]
    public class DataLinkParameter : ICSSoft.STORMNET.DataObject
    {
        
        private string fObjectField;
        
        private string fLayerField;
        
        private string fExpression;
        
        private bool fLinkField = false;
        
        private NewPlatform.Flexberry.GIS.DataLink fLink;
        
        // *** Start programmer edit section *** (DataLinkParameter CustomMembers)

        // *** End programmer edit section *** (DataLinkParameter CustomMembers)

        
        /// <summary>
        /// ObjectField.
        /// </summary>
        // *** Start programmer edit section *** (DataLinkParameter.ObjectField CustomAttributes)

        // *** End programmer edit section *** (DataLinkParameter.ObjectField CustomAttributes)
        [StrLen(255)]
        public virtual string ObjectField
        {
            get
            {
                // *** Start programmer edit section *** (DataLinkParameter.ObjectField Get start)

                // *** End programmer edit section *** (DataLinkParameter.ObjectField Get start)
                string result = this.fObjectField;
                // *** Start programmer edit section *** (DataLinkParameter.ObjectField Get end)

                // *** End programmer edit section *** (DataLinkParameter.ObjectField Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DataLinkParameter.ObjectField Set start)

                // *** End programmer edit section *** (DataLinkParameter.ObjectField Set start)
                this.fObjectField = value;
                // *** Start programmer edit section *** (DataLinkParameter.ObjectField Set end)

                // *** End programmer edit section *** (DataLinkParameter.ObjectField Set end)
            }
        }
        
        /// <summary>
        /// LayerField.
        /// </summary>
        // *** Start programmer edit section *** (DataLinkParameter.LayerField CustomAttributes)

        // *** End programmer edit section *** (DataLinkParameter.LayerField CustomAttributes)
        [StrLen(255)]
        public virtual string LayerField
        {
            get
            {
                // *** Start programmer edit section *** (DataLinkParameter.LayerField Get start)

                // *** End programmer edit section *** (DataLinkParameter.LayerField Get start)
                string result = this.fLayerField;
                // *** Start programmer edit section *** (DataLinkParameter.LayerField Get end)

                // *** End programmer edit section *** (DataLinkParameter.LayerField Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DataLinkParameter.LayerField Set start)

                // *** End programmer edit section *** (DataLinkParameter.LayerField Set start)
                this.fLayerField = value;
                // *** Start programmer edit section *** (DataLinkParameter.LayerField Set end)

                // *** End programmer edit section *** (DataLinkParameter.LayerField Set end)
            }
        }
        
        /// <summary>
        /// Expression.
        /// </summary>
        // *** Start programmer edit section *** (DataLinkParameter.Expression CustomAttributes)

        // *** End programmer edit section *** (DataLinkParameter.Expression CustomAttributes)
        [StrLen(255)]
        public virtual string Expression
        {
            get
            {
                // *** Start programmer edit section *** (DataLinkParameter.Expression Get start)

                // *** End programmer edit section *** (DataLinkParameter.Expression Get start)
                string result = this.fExpression;
                // *** Start programmer edit section *** (DataLinkParameter.Expression Get end)

                // *** End programmer edit section *** (DataLinkParameter.Expression Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DataLinkParameter.Expression Set start)

                // *** End programmer edit section *** (DataLinkParameter.Expression Set start)
                this.fExpression = value;
                // *** Start programmer edit section *** (DataLinkParameter.Expression Set end)

                // *** End programmer edit section *** (DataLinkParameter.Expression Set end)
            }
        }
        
        /// <summary>
        /// LinkField.
        /// </summary>
        // *** Start programmer edit section *** (DataLinkParameter.LinkField CustomAttributes)

        // *** End programmer edit section *** (DataLinkParameter.LinkField CustomAttributes)
        public virtual bool LinkField
        {
            get
            {
                // *** Start programmer edit section *** (DataLinkParameter.LinkField Get start)

                // *** End programmer edit section *** (DataLinkParameter.LinkField Get start)
                bool result = this.fLinkField;
                // *** Start programmer edit section *** (DataLinkParameter.LinkField Get end)

                // *** End programmer edit section *** (DataLinkParameter.LinkField Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DataLinkParameter.LinkField Set start)

                // *** End programmer edit section *** (DataLinkParameter.LinkField Set start)
                this.fLinkField = value;
                // *** Start programmer edit section *** (DataLinkParameter.LinkField Set end)

                // *** End programmer edit section *** (DataLinkParameter.LinkField Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.GIS.DataLink.
        /// </summary>
        // *** Start programmer edit section *** (DataLinkParameter.Link CustomAttributes)

        // *** End programmer edit section *** (DataLinkParameter.Link CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Link"})]
        public virtual NewPlatform.Flexberry.GIS.DataLink Link
        {
            get
            {
                // *** Start programmer edit section *** (DataLinkParameter.Link Get start)

                // *** End programmer edit section *** (DataLinkParameter.Link Get start)
                NewPlatform.Flexberry.GIS.DataLink result = this.fLink;
                // *** Start programmer edit section *** (DataLinkParameter.Link Get end)

                // *** End programmer edit section *** (DataLinkParameter.Link Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DataLinkParameter.Link Set start)

                // *** End programmer edit section *** (DataLinkParameter.Link Set start)
                this.fLink = value;
                // *** Start programmer edit section *** (DataLinkParameter.Link Set end)

                // *** End programmer edit section *** (DataLinkParameter.Link Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "DataLinkParameterD" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DataLinkParameterD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DataLinkParameterD", typeof(NewPlatform.Flexberry.GIS.DataLinkParameter));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of DataLinkParameter.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfDataLinkParameter CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfDataLinkParameter CustomAttributes)
    public class DetailArrayOfDataLinkParameter : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.GIS.DetailArrayOfDataLinkParameter members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.GIS.DetailArrayOfDataLinkParameter members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type DataLinkParameter by index.
        /// </summary>
        /// <summary>
        /// Adds object with type DataLinkParameter.
        /// </summary>
        public DetailArrayOfDataLinkParameter(NewPlatform.Flexberry.GIS.DataLink fDataLink) : 
                base(typeof(DataLinkParameter), ((ICSSoft.STORMNET.DataObject)(fDataLink)))
        {
        }
        
        public NewPlatform.Flexberry.GIS.DataLinkParameter this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.GIS.DataLinkParameter)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.GIS.DataLinkParameter dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
